# Generated by Django 3.1.5 on 2021-06-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20210603_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Default snippet text', max_length=300),
        ),
    ]
